DROP DATABASE IF EXISTS aurajoen_courses_new;
CREATE DATABASE IF NOT EXISTS aurajoen_courses_new DEFAULT CHARSET utf8 DEFAULT COLLATE utf8_swedish_ci;

USE aurajoen_courses_new;

CREATE TABLE IF NOT EXISTS account (

	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,

	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS person (
	
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	account_id INTEGER NOT NULL,
	
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	birthday DATE NOT NULL,
	notes TEXT NOT NULL DEFAULT '',

	FOREIGN KEY (account_id) REFERENCES account(id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS address (

	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	person_id INTEGER NOT NULL,
	
	street_address VARCHAR(255) NOT NULL,
	zipcode INTEGER NOT NULL,
	post_office VARCHAR(255) NOT NULL,

	FOREIGN KEY (person_id) REFERENCES person(id)	
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS season (

	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
	season_start YEAR NOT NULL,
	season_end YEAR NOT NULL,

	UNIQUE (season_start, season_end)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS place (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	address VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS product (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT NOT NULL default ''
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS course_event (

	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	product_id INTEGER NOT NULL,
	season_id INTEGER NOT NULL,
	place_id INTEGER NOT NULL,

	period enum('Q1','Q2','H1','Q3','Q4','H2','SUMMER') COLLATE utf8_swedish_ci DEFAULT NULL,
	weekday INTEGER NOT NULL,
	start_time TIME,
	end_time TIME,

	regstartdate DATE NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL,

	notes TEXT NOT NULL default '',

	max_participants INTEGER,
	price DECIMAL(6,2) NOT NULL,
	member_price DECIMAL(6,2) NOT NULL,

	FOREIGN KEY (product_id) REFERENCES product(id),
	FOREIGN KEY (season_id) REFERENCES season(id),
	FOREIGN KEY (place_id) REFERENCES place(id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS participant (
	
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	person_id INTEGER NOT NULL,
	event_id INTEGER NOT NULL,
	enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

	FOREIGN KEY (person_id) REFERENCES person(id),
	FOREIGN KEY (event_id) REFERENCES course_event(id)
	UNIQUE (person_id, event_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS sibling (

	person_id INTEGER NOT NULL,
	sibling_id INTEGER NOT NULL,
	
	PRIMARY KEY (person_id, sibling_id),
	FOREIGN KEY (person_id) REFERENCES person(id),
	FOREIGN KEY (sibling_id) REFERENCES person(id)

) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS membership (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	season_id INTEGER NOT NULL,
	price DECIMAL(5,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS member (
	
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	membership_id INTEGER NOT NULL,
	person_id INTEGER NOT NULL,

	FOREIGN KEY (membership_id) REFERENCES membership(id),
	FOREIGN KEY (person_id) REFERENCES person(id),
	UNIQUE (membership_id, person_id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_swedish_ci;

CREATE TABLE IF NOT EXISTS reskontra (
	id INTEGER NOT NULL PRIMARY KEY,
	account_id INTEGER NOT NULL,
	sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
)
